name: Fullstack Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: exp-16/Testing/Backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: pytest

  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: exp-16/Testing/Frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install
      - run: npm test